### ISSUE TITLE
Question: What is the difference between "Shuffle" and "Random"?

### ISSUE THREAD

**Issue by jrkanu** [OatmealDome/SplatoonUtilities#2]
I actually haven't used the Random option yet so I was just wondering.

Btw, thanks for the app, I'm really loving it. 👍

**Comment by OatmealDome** [comment]
"Shuffle" makes it so that each track in a list (multiplayer BGM, one minute, single player mission BGM) will  all play at least once before repeats. "Random" will simply pick a track to play at random; it doesn't matter if the track has already been played right before.

Thanks for your support!

**Comment by jrkanu** [comment]
Thanks! One more question while I have you, how do I use the "Play Next" button? I get an unhandled exception error whenever I try it so I'm not sure if I'm using it correctly. I thought it was to switch tracks mid-battle but that doesn't seem to work (I've only tried a few times). Or is it for choosing a specific track to play next battle?

**Comment by OatmealDome** [comment]
"Play Next" will force the track you select in the track list to, well, play next. Switching tracks mid battle isn't really something that's possible due to how the game works. So, if you select "Play Next" on a track mid battle, depending on at what the timer is, the track will play either at one minute remaining or at the matchmaking screen.

The unhandled exception is due to a bug, which will be fixed in the next release.

**Comment by jrkanu** [comment]
Ah, that makes sense, thanks for exaining! I'll go ahead and close this now. :)
